# This service definition provides the capabilities report for a NEPI IDX sensor

---
# NEX Generic Parameters
bool has_standby_mode

# IDX Generic Parameters
bool adjustable_resolution
bool adjustable_framerate
bool adjustable_contrast
bool adjustable_brightness
bool adjustable_thresholding
bool adjustable_range
bool auto_adjustment

# IDX Generic Data Outputs
bool has_image
bool has_depth_map
bool has_pointcloud

# Data products supported by IDX node is a string of supported data products that can be subscribed to or saved
# DATA_PRODUCTS = ["image","depth_map","pointcloud","pointcloud_image]
string[] data_products
# Then the actual types for each data product name
# DATA_PRODUCT_TYPES = ["image","depth_map","pointcloud","image"]
string[] data_product_types


