# This service definition provides the capabilities report for a NEPI IDX sensor

---
# Image data product type
# SUPPORTED_DATA_PRODUCTS = ['image','color_image','bw_image',
#                            'intensity_map','depth_map','pointcloud']
string data_product_type

# List of data product names provided by class
string[] data_products

string[] frame_id_options

bool has_resolution
bool has_contrast
bool has_brightness
bool has_thresholding
bool has_range
bool has_auto_adjust
bool has_zoom
bool has_pan
bool has_window
bool has_rotate
bool has_tilt

# If supported

bool has_depth_map
string depth_map_topic

bool has_point_cloud
string pointcloud_topic




