# This service definition provides the navpose capabilities report for a general NEPI NEX driver node

---
bool has_heading
bool has_position
bool has_orientation
bool has_location
bool has_altitude
bool has_depth

bool has_gps_pub
bool has_elevation_pub
bool has_pose_pub
bool has_heading_pub


float32[] pub_rate_min_max
string[] frame_id_options
string[] frame_3d_options
string[] frame_altitude_options

