# This service definition provides the capabilities report for a NEPI PTX (pan/tilt) actuator

---
bool has_adjustable_speed
bool has_absolute_positioning
bool has_timed_positioning
bool has_seperate_pan_tilt
bool has_auto_pan
bool has_auto_tilt
bool has_homing
bool has_waypoints
